blank_issues_enabled: false
contact_links:
  - name: Telegram
    url: https://t.me/lo2cin4group
    about: Community and collaboration contact.
  - name: Discord
    url: https://discord.gg/sSnZuq3DNu
    about: Community questions and discussion.
